image: Visual Studio 2017
configuration:
  - Release
before_build:
  - nuget restore
build:
  project: StreamerNotifications.sln
  verbosity: normal
version: 1.0.0.{build}
install:
  - ps: AppVeyor\install.ps1
skip_commits:
  files:
    - AppVeyor/**/*
    - docs/**/*
    - '**/*.md'
